Config-offerings utilisation behaviors
Geoplateforme/sdk-entrepot pull request #36
Opened 2023-10-04 14:04 UTC by LudivineSchlegel

Première partie de la résolution du #29 
Prise en compte des behaviors pour les configurations et les offres.

Il restera à traité la question de l'ajout ou non des suppression en cascade (offre, [configuration, [stored-data]]) : nouvelle option ou comportement de base de DELETE

2023-10-06 14:56 UTC, vsasyan-ignf requested changes
Du coup j'ai pas mal de questions ^^

2023-10-06 14:56 UTC, vsasyan-ignf commented on ignf_gpf_sdk/__main__.py
> +    }
Ce n'est pas homogène. Il faudra qu'on tranche ce qui doit être choisi.

2023-10-06 14:56 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/Configuration.py
> +        """
```suggestion
        """Fonction de suppression de la Configuration en supprimant en cascade les offres liées (et uniquement les offres, pas les données stockées).

        Args:
            before_delete (Optional[Callable[[List[StoreEntity]], List[StoreEntity]]], optional): fonction à lancer avant la suppression (entrée : liste des entités à supprimer,
                sortie : liste définitive des entités à supprimer). Defaults to None.
        """
```

2023-10-06 14:56 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoreEntity.py
> +        """
```suggestion
        """Suppression d'une liste d’entités. Exécution de `before_delete(l_entities)` avant la suppression, before_delete retourne la nouvelle liste des éléments à supprimer.

        Args:
            l_entities (List[StoreEntity]]): liste des entités à supprimer
            before_delete (Optional[Callable[[List[StoreEntity]], List[StoreEntity]]], optional): fonction à lancer avant la suppression (entrée : liste des entités à supprimer,
                sortie : liste définitive des entités à supprimer). Defaults to None.
        """
```

2023-10-06 14:56 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoreEntity.py
> +        Config().om.info("Suppression effectué.", green_colored=True)
```suggestion
        Config().om.info("Suppression effectuée.", green_colored=True)
```

2023-10-06 14:56 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoredData.py
> +        """
```suggestion
        """Suppression de la donnée stockée avec suppression en cascade des configuration liées et des offres liées à chaque configuration.

        Args:
            before_delete (Optional[Callable[[List[StoreEntity]], List[StoreEntity]]], optional): fonction à lancer avant la suppression (entrée : liste des entités à supprimer,
                sortie : liste définitive des entités à supprimer). Defaults to None.
        """
```

2023-10-06 14:56 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoredData.py
> +        # suppression d'une stored_data : uniquement l'upload, configuration et stored_data
Je ne comprends pas ce commentaire.

2023-10-23 12:39 UTC, LudivineSchlegel commented on ignf_gpf_sdk/__main__.py
> +    }
Je te laisse harmonisé les nommages (anglais ou français)

2023-10-23 12:41 UTC, LudivineSchlegel commented on ignf_gpf_sdk/store/StoredData.py
> +        # suppression d'une stored_data : uniquement l'upload, configuration et stored_data
```suggestion
        # suppression d'une stored_data : l'upload, configuration et stored_data
```
un "copier coller modifier" qui est mal passé ...

2023-10-25 07:24 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoredData.py
> +        # suppression d'une stored_data : uniquement l'upload, configuration et stored_data
Du coup c'est même offering, configuration et stored_data

2023-10-25 07:26 UTC, LudivineSchlegel commented on ignf_gpf_sdk/store/StoredData.py
> +        # suppression d'une stored_data : uniquement l'upload, configuration et stored_data
```suggestion
        # suppression d'une stored_data : uniquement l'offering, configuration et stored_data
```
en effet ...

2023-10-25 07:27 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoredData.py
> +        # suppression d'une stored_data : uniquement l'upload, configuration et stored_data
```suggestion
        # suppression d'une stored_data : offering et configuration liées puis la stored_data
```

2023-10-25 07:28 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoredData.py
> +        """suppression en cascade des offres : uniquement les offres
```suggestion
        """suppression en cascade d'une stored_data : listing puis suppression des offering et configurations liées.

2023-10-25 07:30 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoreEntity.py
> +        """suppression en cascade des offres : uniquement les offres
```suggestion
        """Suppression en cascade d'une stored_data en supprimant en cascade les offering et les configurations liées.
```

2023-10-25 07:32 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoreEntity.py
> +        """Suppression en cascade d'une stored_data en supprimant en cascade les offering et les configurations liées.
```suggestion
        """Suppression en cascade d'une entité en supprimant les entités liées (qui vont dépendre du type de l'entité, donc cf. les classes filles).
```

2023-10-25 07:33 UTC, vsasyan-ignf commented on ignf_gpf_sdk/store/StoreEntity.py
> +        """
```suggestion
            before_delete (Optional[Callable[[List[StoreEntity]], List[StoreEntity]]], optional): fonction à lancer avant la suppression (entrée : liste des entités à supprimer,
                sortie : liste définitive des entités à supprimer). Defaults to None.
        """
```

2023-11-15 10:26 UTC, vsasyan-ignf approved these changes

2023-11-15 10:26 UTC, merged