Public doc
Geoplateforme/sdk-entrepot pull request #76
Opened 2024-02-12 14:19 UTC by vsasyan-ignf

Corrections mineurs doc :

* correction liens
* correction admonitions
* doc déploiement de la doc

2024-02-12 14:20 UTC, vsasyan-ignf commented
Pour les blocs info/warning (les admonitions), j'ai vu que tu avais changé la syntaxe, chez moi ça ne fonctionnait plus :/

C'est pour que ça passe avec Github ?

2024-02-12 14:50 UTC, LudivineSchlegel commented
oui, c'est pour github par exemple : https://github.com/Geoplateforme/sdk-entrepot/blob/prod/docs/comme-module.md#avec-la-classe-uploadaction

2024-02-12 15:10 UTC, LudivineSchlegel requested changes
Il faut revoir la compatibilité avec la doc en ligne et la doc github

Note et warning => non affichable sous github et contre productif
les liens modifié sont tous mort dans github sauf liens vers les fichiers du sdk (donc vers gitbub en dur)

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/resolveurs.md
> +* `store_entity` : un [StoreEntityResolver](reference/workflow/resolver.md/#sdk_entrepot_gpf.workflow.resolver.StoreEntityResolver.StoreEntityResolver)
ne fonctionne pas sous github : https://github.com/Geoplateforme/sdk-entrepot/blob/2b22795011eda903682ed55aebd19817ee27b704/docs/resolveurs.md

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/resolveurs.md
> +* [UserResolver](reference/workflow/resolver.md/#sdk_entrepot_gpf.workflow.resolver.UserResolver.UserResolver): récupère des informations de l'utilisateur courant depuis la GPF.
ne fonctionne pas sous github

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/workflow.md
> +* [modifier une entité](#modifier-une-entite)
ne fonctionne pas sous github : https://github.com/Geoplateforme/sdk-entrepot/blob/2b22795011eda903682ed55aebd19817ee27b704/docs/workflow.md#modifier-une-entit%C3%A9

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/workflow.md
> +* [exécuter un traitement](#executer-un-traitement)
ne fonctionne pas sous github : https://github.com/Geoplateforme/sdk-entrepot/blob/2b22795011eda903682ed55aebd19817ee27b704/docs/workflow.md#ex%C3%A9cuter-un-traitement

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/workflow.md
> +* [supprimer une entité](#supprimer-une-entite)
ne fonctionne pas sous github : https://github.com/Geoplateforme/sdk-entrepot/blob/2b22795011eda903682ed55aebd19817ee27b704/docs/workflow.md#supprimer-une-entit%C3%A9

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/workflow.md
> +```json
passage de jsonc à json créer des lignes rouges dans tout le code :
https://github.com/Geoplateforme/sdk-entrepot/blob/2b22795011eda903682ed55aebd19817ee27b704/docs/workflow.md#supprimer-une-entit%C3%A9

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/configuration.md
affichage non pris en compte sous github 
![Capture du 2024-02-12 16-04-49](https://github.com/Geoplateforme/sdk-entrepot/assets/35892777/8052e8c0-9e85-4a32-815a-7e90c1bdf494)

fin de la partie : https://github.com/Geoplateforme/sdk-entrepot/blob/2b22795011eda903682ed55aebd19817ee27b704/docs/configuration.md#votre-fichier-de-configuration

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/comme-module.md
> +
affichage non pris en compte sous github
![Capture du 2024-02-12 16-06-09](https://github.com/Geoplateforme/sdk-entrepot/assets/35892777/5b613d86-ddb4-4018-a7a4-e3fbcda8c2f9)

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/comme-module.md
> +    ```
affichage non pris en compte sous github
![Capture du 2024-02-12 16-06-09](https://github.com/Geoplateforme/sdk-entrepot/assets/35892777/5b613d86-ddb4-4018-a7a4-e3fbcda8c2f9)

2024-02-12 15:10 UTC, LudivineSchlegel commented on docs/comme-executable.md
> +
affichage non pris en compte sous github
![Capture du 2024-02-12 16-07-50](https://github.com/Geoplateforme/sdk-entrepot/assets/35892777/d9b1749d-92ea-4da7-8cb7-ba5034233e02)

2024-02-19 07:53 UTC, LudivineSchlegel commented on docs/workflow.md
> +```json
obligatoire pour la doc en ligne

2024-02-19 07:57 UTC, LudivineSchlegel requested changes
toujours problème de liens dans docs/workflow.md il faut essayer les liens caché:
ajouté `<a id="nom"></a>` et faire référence à "nom" dans les liens vers le paragraphe

2024-02-19 07:57 UTC, LudivineSchlegel commented on docs/resolveurs.md
> +* `store_entity` : un [StoreEntityResolver](reference/workflow/resolver.md/#sdk_entrepot_gpf.workflow.resolver.StoreEntityResolver.StoreEntityResolver)
corrigé

2025-02-12 15:09 UTC, merged