Copy configuration. Close #77
Geoplateforme/sdk-entrepot pull request #79
Opened 2024-02-13 14:32 UTC by LudivineSchlegel

Correction de #77 

## [Changed]

* Renommage de `CopieConfigurationAction` en `CopyConfigurationAction`

## [Fixed]

* problème de nommage de l'action de copie de configuration entre le code est la doc : utilisation de `copy-configuration`

2024-02-20 11:17 UTC, vsasyan-ignf requested changes
pt pb dans le change log

2024-02-20 11:17 UTC, vsasyan-ignf commented on CHANGELOG.md
> +* Upload: modification de la requête suite modification de l'API GPF #54
Ca devrait être l'inverse, non ?

Le "Upload:" dans la v0.1.21 et le "Bug #77" dans la v0.1.22

2024-02-20 11:36 UTC, LudivineSchlegel commented on CHANGELOG.md
> +* Upload: modification de la requête suite modification de l'API GPF #54
oui je corrige ça ! je me suis trompée de ligne

2024-03-04 08:29 UTC, vsasyan-ignf approved these changes

2024-03-04 08:29 UTC, merged